# См. статью по ссылке https://aka.ms/customizecontainer, чтобы узнать как настроить контейнер отладки и как Visual Studio использует этот Dockerfile для создания образов для ускорения отладки.

# Этот этап используется при запуске из VS в быстром режиме (по умолчанию для конфигурации отладки)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /app
EXPOSE 8080

# Этот этап используется для сборки проекта службы
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY *.csproj ./Mathematics.Addition/
RUN dotnet restore Mathematics.Addition/Mathematics.Addition.csproj

COPY . ./Mathematics.Addition/
RUN dotnet build Mathematics.Addition/Mathematics.Addition.csproj -c $BUILD_CONFIGURATION -o /app/build

# Этот этап используется в рабочей среде или при запуске из VS в обычном режиме (по умолчанию, когда конфигурация отладки не используется)
FROM base AS final
WORKDIR /app
COPY --from=build  /app/build .
ENTRYPOINT ["dotnet", "Mathematics.Addition.dll"]